apiVersion: v1
kind: Template
metadata:
  annotations:
    description: A ready to use WordPress
    iconClass: icon-wordpress
    tags: instant-app, wordpress, kermit
  name: wordpress
labels:
  app: wordpress
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: php
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: php:5.6-apache
      from:
        kind: DockerImage
        name: php:5.6-apache
      importPolicy: {}
      name: 5.6-apache
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      name: mysql
    name: ${APPLICATION_NAME}-mysql-pvclaim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      name: html
    name: ${APPLICATION_NAME}-html-pvclaim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mysql
    name: mysql
  spec:
    replicas: 1
    selector:
      app: mysql
      deploymentconfig: mysql
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.mysql.image.entrypoint: '["container-entrypoint","run-mysqld"]'
        labels:
          app: mysql
          deploymentconfig: mysql
      spec:
        containers:
        - image: openshift/mysql:5.6
          env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: WORDPRESS_DB_HOST
            value: mysql
          - name: WORDPRESS_DB_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: WORDPRESS_DB_NAME
            value: ${MYSQL_DATABASE}
          - name: WORDPRESS_DB_USER
            value: ${MYSQL_USER}  
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: mysql-volume-1
        volumes:
        - name: mysql-volume-1
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-mysql-pvclaim
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.6
          namespace: openshift
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql
    name: mysql
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql
      deploymentconfig: mysql
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:        
      git:
        uri: ${GIT_REPOSITORY_URL}
        ref: master
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: php:5.6-apache
        env:
        - name: HTTPS_PROXY
          value: http://proxy-internet.internal.fr:3128
        - name: HTTP_PROXY
          value: http://proxy-internet.internal.fr:3128
        - name: http_proxy
          value: http://proxy-internet.internal.fr:3128
        - name: https_proxy
          value: http://proxy-internet.internal.fr:3128        
      type: Docker
    triggers:
    - github:
        secret: ${WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${WEBHOOK_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.${APPLICATION_NAME}.image.entrypoint: '["apache2-foreground"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: WORDPRESS_DB_HOST
            value: mysql
          - name: WORDPRESS_DB_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: WORDPRESS_DB_NAME
            value: ${MYSQL_DATABASE}
          - name: WORDPRESS_DB_USER
            value: ${MYSQL_USER}
          image: library/${APPLICATION_NAME}:latest
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/www/html
            name: volume-html
          - mountPath: /var/lock/apache2
            name: volume-lock
          - mountPath: /var/log/apache2
            name: volume-log
          - mountPath: /var/run/apache2
            name: volume-run
          - mountPath: /var/run/sshd
            name: volume-sshd           
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-html
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-html-pvclaim
        - emptyDir: {}
          name: volume-lock
        - emptyDir: {}
          name: volume-log
        - emptyDir: {}
          name: volume-run
        - emptyDir: {}
          name: volume-sshd          
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow    
parameters:
  -
    description: "The name assigned to all of the objects defined in this template."
    displayName: APPLICATION_NAME
    name: APPLICATION_NAME
    required: true
    value: wpkmt
  -
    description: "The URL of your wordpress repository"
    displayName: GIT_REPOSITORY_URL
    name: GIT_REPOSITORY_URL
    required: true
    value: "https://github.com/cyril-dussert/wordpress.git"
  -
    description: "Username of database account"
    displayName: MYSQL_USER
    name: MYSQL_USER
    required: true
    value: dbuser
  -
    description: "Name of database"
    displayName: MYSQL_DATABASE
    name: MYSQL_DATABASE
    required: true
    value: wpkmtdb
  -
    description: "Password for database account"
    displayName: MYSQL_PASSWORD
    from: "[a-zA-Z0-9]{15}"
    generate: expression
    name: MYSQL_PASSWORD
    required: true
  -
    description: "A secret string used to configure the Git webhook."
    displayName: "Git Webhook Secret"
    from: "[a-zA-Z0-9]{40}"
    generate: expression
    name: WEBHOOK_SECRET